config/routes.rb
Rails.application.routes.draw do
  root to: 'hostel_operation#index'
  devise_for :users, controllers: {registrations: 'user/registrations' , sessions: 'user/sessions' }
  get 'owner/all_request'
  get 'owner/student_profile'
  get 'leave/show_owner'
  get 'room_management/get_all_room'
  resources :payment
  resources :hostel_operation
  post 'hostel_operation/check_auth'
  resources :room_management
  resources :owner
  resources :student do
    resources :leave
    resources :hostelfee
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/student_controller.rb
class StudentController < ApplicationController
    def index
         @user=User.find(current_user.id)
         @room_members=User.where(room_no:@user.room_no)
         @total_rooms=Room.all.size
         @total_capacity=Room.sum('capacity');
         @total_vacancy=Room.sum('vacancy');
     end

    # def index
    #     @user=Hosteler.find(current_hosteler.id)
    #     @room_members=User.where(room_no:@user.room_no)
    #     @total_rooms=Room.all.size
    #     @total_capacity=Room.sum('capacity');
    #     @total_vacancy=Room.sum('vacancy');
    # end
end

app/helpers/student_helper.rb
module StudentHelper
end

app/views/student/_header.html.erb
<nav class="navbar navbar-expand-sm text-white navbar-dark" style="border:2px solid black;background-color: #FF5C20;font-family: Montserrat, sans-serif;">  
    
  	<h1 style="margin-left:20%"><b>Hostel Management System</b></h1>
  	<%if current_user.ProfilePic.attached?%>
  	<image src=<%=url_for(current_user.ProfilePic)%> alt="logo" style="width:7%;border-radius: 50%;margin-left:35%"> 
  		<%end%>
</nav>

app/views/student/_menu.html.erb
<table class="table table-hover table-striped" style="width:20%;background-color:#f4511e;float:left">
		<thead class="thead-dark">
			<tr>
				<th >Dashboard<i class="fa fa-dashboard  float-right" style="font-size:24px;color:white"></i>
				</th>
			</tr>
		</thead>
		<tbody>
			<tr>
				<th class="text-warning"><a href="#" class="link text-white"><div style="height:100%;width:100%;"><i class='fas fa-home' style='font-size:35px;color:white;'></i><x class="ml-4" style="color:black"><b>Home</b></x></div></a>
				</th>
     		</tr>
     		<tr>
				<th class="text-warning"><a href="#" class="link text-white"><div style="height:100%;width:100%;"><i class='fas fa-upload' style='font-size:35px;color:white;'></i><x class="ml-4" style="color:black"><b><%= link_to 'Hostel Fee', student_hostelfee_index_path(current_user.id) ,class:"link text-white"%></b></x></div></a>
				</th>
     		</tr>
      		<tr>
    			<th><div style="height:100%;width:100%"><i class='fa fa-building' style='font-size:35px;color:white'></i><x class="ml-4" style="color:black"><b> <%= link_to 'Leave Application', student_leave_index_path(current_user.id) ,class:"link text-white"%></b></x></div>
    			</th>
    		</tr>
    		 <tr>
  			    <th><a href="#" class="link text-white"><div style="height:100%;width:100%"><i class='fas fa-bed' style='font-size:35px;color:white'></i><x class="ml-4" style="color:black"><b>Guests Stay Request</b></x></div></a>
  			    </th>
  			</tr> 
  			
     		<tr>
    			<th ><a href="#" class="link text-white"><div style="height:100%;width:100%"><i class='fa fa-cutlery' style='font-size:35px;color:white'></i><x class="ml-4" style="color:black"><b> Food Coupon Apply</b></x> </div></a>
    			</th>
    		</tr>
    		
    		<tr>
    			<th ><a href="#" class="link text-white"><div style="height:100%;width:100%"><i class='fas fa-exclamation-circle' style='font-size:35px;color:white'></i><x class="ml-4" style="color:black"><b> Complain</b></x></div></a>
    			</th>
    		</tr>
    		
    		<tr>
    			<th ><a href="#" class="link text-white"><div style="height:100%;width:100%"><i class='fa fa-users' style='font-size:35px;color:white'></i><x class="ml-4" style="color:black"><b>Visitor</b></x></div></a>
    			</th>
    		</tr>
     		
     		<tr>
    			<th ><div style="height:100%;width:100%"><i class='fa fa-sign-out' style='font-size:35px;color:white'></i><x class="ml-4" style="color:black"><b>
				<%= button_to 'Logout', destroy_user_session_path,class:"btn btn-danger",method:'delete',style:'margin-top:-10%;margin-left:35%'%>
    			</th>
    		</tr>
    		
		</tbody>

</table>

app/views/student/index.html.erb
<%= render 'header' %>
<%= render 'menu' %>
<div style="height:auto;width:70%;margin-top:2%;margin-left:25%;border:2px solid orange;border-radius:5%" class=" mb-5 bg-light">
	   			<h3 class="pt-4 text-center"><b> Hello <%=@user.firstname%> Welcome To Room No <%=@user.room_no%></b></h3>
	   			<hr><br>
		   			
		   				<div class="row pl-5">
						    <div class="col">
						    	<center><h5><b>Room Members:</b></h5></center>
						    </div>
						  </div><br>
						  
						  <div class="row pl-5">
							    <%@room_members.each do |member|%>
							    <div class="col">
							      	<b>Name= <%=member.firstname%> <%=member.lastname%><br>
							      	Phone no=<%=member.phoneno%></b>
							     </div>
							     <%end%>
						  </div><br><br>
						  
						   <div class="row pl-5">
							   <div class="col">
							    	<center> <h5><b>Hostel Information:</b></h5></center>
							    </div>
						  </div><br>
							  
						  <div class="row pl-5">
							   <div class="col">
							    	<h5><b>About no of room:</b></h5>
							    </div>
						  </div>
						  
						  <div class="row pl-5">
							    <div class="col">
							    	<b>Total no of room = <%=@total_rooms%></b>
							    </div>
							    <div class="col">
							    	<b>No of student's room = <%=@total_rooms%></b>
							    </div>
							    <div class="col">
							    	<b>No of guest's rooms = 0</b>
							    </div>
						  </div><br>
						  
						  <div class="row pl-5">
							   <div class="col">
							    	<h5><b>About capacity of hostel:</b></h5>
							    </div>
						  </div>
						  
						  <div class="row pl-5">
							    <div class="col">
							    	<b>Capacity for students = <%=@total_capacity%></b>
							    </div>
							    <div class="col">
							    	<b>No of students in hostel  = <%=@total_capacity-@total_vacancy%></b>
							    </div>
							    <div class="col">
							    	<b>Vacancy in hostel = <%=@total_vacancy%></b>
							    </div>
						  </div><br>
						   
						   
					
	   		</div>