config/routes.rb
Rails.application.routes.draw do
  root to: 'hostel_operation#index'
  devise_for :users, controllers: {registrations: 'user/registrations' , sessions: 'user/sessions' }
  get 'owner/all_request'
  get 'owner/student_profile'
  get 'leave/show_owner'
  get 'room_management/get_all_room'
  resources :payment
  resources :hostel_operation
  post 'hostel_operation/check_auth'
  resources :room_management
  resources :owner
  resources :student do
    resources :leave
    resources :hostelfee
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/room_management_controller.rb
class RoomManagementController < ApplicationController

    def index
        @rooms=Room.all.size
    end
    def show
        @users=User.where(room_no:params[:id])
    end
    
    def get_all_room
        @rooms=Room.all
    end

    def new
        @room = Room.new;
    end

    def create
        @room=Room.new(get_params)
    
        if @room.save
            flash[:RoomAlert]='Room Created Successfully'
            index()
            render 'index'
        else
            render 'new'
        end
    end

    def get_params
        params.require(:room).permit(:room_no,:capacity,:vacancy)
    end
    
end

app/helpers/room_management_helper.rb
module RoomManagementHelper
end

app/views/room_management/get_all_room.html.erb
<%= render 'owner/header' %>
<%= render 'owner/menu' %>
<%i=1%>
<div style="height:auto;width:60%;margin-top:5%;margin-left:30%;border:2px solid orange;border-radius:5%" class="bg-light">
	   			<h2 class="pt-4 text-center "><b>Room Information</b></h2>
	   			<hr>
		   			<table class="table table-stripped table-hover table-bordered">
		   	<tr class="table-danger">		
		   	<td><b>No.</b></td>
			<td><b>Room No</b></td>
			<td><b>Capacity Of Room</b></td>
			<td><b>Current Member In Room</b></td>
			<td><b>View Room</b></td>
			</tr>
			
			
			 <%@rooms.each do |room|%>	
			<tr>	
		   	<td><b><%=i%></b></td>
			<td><b><%=room.room_no%></b></td>
			<td><b><%=room.capacity%></b></td>
			<td><b><%=room.capacity-room.vacancy%></b></td>
			<td><center><b><%=link_to 'View Room', room_management_path(room.id)%></b></center></td>
			</tr><%i=i+1%>
			<%end%>	   			
		   			</table>
	   		</div>
</div>

app/views/room_management/index.html.erb
<%= render 'owner/header' %>
<%= render 'owner/menu' %>
<div class="container">
<%if flash[:RoomAlert]%>
      <%=flash[:RoomAlert]%>
      <%end%>
	<div class="row mt-3">
			<div class="col-lg-6 col-md-6 col-12" style="border:0px solid black">
			 <div class="card mt-5 ml-5 " style="border:2px solid orange;width:80%; float:left;border-radius:7%">
				  <center><i class='fa fa-info-circle mt-2' style='font-size:100px;color:#FC3900'></i></center>
				  <hr>
				  <div class="row" style="height:auto;width:100%;border:0px solid black">
				  	<div class="col col-7"><h4 class="ml-3 mt-1"><%= link_to 'Room Information',room_management_get_all_room_path,class:"link text-black"%></b></h4>
				  	</div>
				  	<div class="col col-2"><div style="height:90%;width:1%;border:2px solid black"></div>
				  	</div>
				  	<div class="col col-3"><h4 class=" mt-1"><b><%=@rooms%></b></h4>
				  	</div>
				  </div>
			</div>
			<a href="deallocaetroom.html"><div class="card mt-5 ml-5" style="border:2px solid orange;width:80%; float:left;border-radius:7%">
					<center><i class='fas fa-exchange-alt mt-2' style='font-size:100px;color:#FC3900'></i></center>
				  <hr>
				  <div class="row" style="height:auto;width:100%;border:0px solid black">
				  	<div class="col col-7"><h4 class="ml-3 mt-1"><b>De-allocate<br>Room</b></h4>
				  	</div>
				  	<div class="col col-2"><div style="height:90%;width:1%;border:2px solid black"></div>
				  	</div>
				  	<div class="col col-3"><h4 class=" mt-1"><b></b></h4>
				  	</div>
				  </div>				 
			</div> </a>
		</div>
		<div class="col-lg-6 col-md-6 col-12" style="border:0px solid black">
			 <div class="card mt-5 ml-5" style="border:2px solid orange;width:80%; float:left;border-radius:7%">
				  <center><i class='fas fa-plus mt-2' style='font-size:100px;color:#FC3900'></i></center>
				  <hr>
				  <div class="row" style="height:auto;width:100%;border:0px solid black">
				  	<div class="col col-7"><h4 class="ml-3 mt-1"><b><%= link_to 'Add Room',new_room_management_path,class:"link text-black"%></h4>
				  	</div>
				  	<div class="col col-2"><div style="height:90%;width:1%;border:2px solid black"></div>
				  	</div>
				  	<div class="col col-3"><h4 class=" mt-1"><b></b></h4>
				  	</div>
				  </div>
			</div>
			<a href="loadremoveroom.html"><div class="card mt-5 ml-5" style="border:2px solid orange;width:80%; float:left;border-radius:7%">
				  <center><i class='fas fa fa-times mt-2' style='font-size:100px;color:#FC3900'></i></center>
				  <hr>
				  <div class="row" style="height:auto;width:100%;border:0px solid black">
				  	<div class="col col-7"><h4 class="ml-3 mt-1"><b>Remove<br> Room</b></h4>
				  	</div>
				  	<div class="col col-2"><div style="height:90%;width:1%;border:2px solid black"></div>
				  	</div>
				  	<div class="col col-3"><h4 class=" mt-1"><b></b></h4>
				  	</div>
				  </div>
			</div></a>
		</div>
	</div>
</div>
</div>

app/views/room_management/new.html.erb
<%= render 'owner/header' %>
<%= render 'owner/menu' %>
<div style="height:auto;width:50%;margin-top:5%;margin-left:35%;border:2px solid orange;border-radius:5%" class="bg-light">
	   			<h2 class="pt-4 text-center"><b>Add Room</b></h2>
	   			<hr>
                   <%=form_for @room,url:room_management_index_path,method:'Post' do |f|%>
						  
						  <div class="row pl-5 pt-4">
						    <div class="col">
						      <label class="pt-2"><b>Room No</b></label>
                              <%=f.text_field :room_no,class:"form-control",style:"width:60%"%>
							  <span style='color:red'><%=@room.errors[:room_no].to_sentence%></span>
						    </div>
						  </div>
						  <div class="row pl-5">
						    <div class="col">
						      <label class="pt-2"><b>Capacity</b></label>
                              <%=f.text_field :capacity,class:"form-control",style:"width:60%"%>
							  <span style='color:red'><%=@room.errors[:capacity].to_sentence%></span>
						    </div>
						  </div>
						  <div class="row pl-5 pb-5">
						    <div class="col">
                            <%=f.submit 'Add Room',class:"btn btn-primary mt-3"%>
						    </div>
						  </div>	  
					
                    <%end%>
	   		</div>

app/views/room_management/show.html.erb
<%= render 'owner/header' %>
<%= render 'owner/menu' %>
<%i=1%>
<div class="container">
	<div class="row mt-5" style="margin-left: 20%">
	<%@users.each do |user|%>	
		<div class="col-lg-6 col-md-6 col-12 mb-3" style="border:0px solid black">
				 <div class="card" style="width:auto;border:2px solid orange;border-radius: 5%;background-color:#FBF3F2 ">
				 	<%if user.ProfilePic.attached?%>
				  <center><div><image class="card-img-top mt-3" src=<%=url_for(user.ProfilePic)%> alt="Card image" style="width:150px;height:150px;"></div></center>
				  	<%end%>
				  <div class="card-body">
				    <center><h4 class="card-title"><%=user.firstname%></h4></center>
				    <p class="card-text"><b>Email-id : <%=user.email%></b></p>
				    <p class="card-text"><b>Phone No : <%=user.phoneno%></b></p>
				    <center><%=link_to "See Profile",owner_student_profile_path(id:user.id)%><b>See Profile</b></center>
				  </div>
				</div>
		</div>
		<%end%>
	</div>
</div>