config/routes.rb
Rails.application.routes.draw do
  root to: 'hostel_operation#index'
  devise_for :users, controllers: {registrations: 'user/registrations' , sessions: 'user/sessions' }
  get 'owner/all_request'
  get 'owner/student_profile'
  get 'leave/show_owner'
  get 'room_management/get_all_room'
  resources :payment
  resources :hostel_operation
  post 'hostel_operation/check_auth'
  resources :room_management
  resources :owner
  resources :student do
    resources :leave
    resources :hostelfee
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/hostelfee.rb
class Hostelfee < ApplicationRecord

	belongs_to :user
end

app/controllers/hostelfee_controller.rb
class HostelfeeController < ApplicationController

	def new 	
		# begin
			if current_user.hostelfee.length==0
				@hostelfee=Hostelfee.new
			elsif current_user.hostelfee[0].year.to_i==Date.today.year
				flash[:notice]='Fee Already Paid'
				redirect_to student_hostelfee_index_path(current_user.id)
			else
				@hostelfee=Hostelfee.new
			end
		 # rescue
		 # 	flash[:notice]='Something Wrong'
		 # 	redirect_to student_hostelfee_index_path(current_user.id)
		 # end
	end

	def show
		@hostelfee=current_user.hostelfee
	end
end

app/helpers/hostelfee_helper.rb
module HostelfeeHelper
end

app/views/hostelfee/index.html.erb
<%= render 'student/header' %>
<%= render 'student/menu' %>
<div class="container">
	<%if flash[:notice]%>
    <%=flash[:notice]%>
    <%end%>

	<div class="row pl-5" style="margin-top:10%;">
		

		<div class="col-sm-6 col-6 pl-5" >
			 <div class="card mt-5 ml-5" style="border:2px solid orange;width:80%; float:left;border-radius:7%">
				  <center><i class='fas fa-upload mt-2' style='font-size:100px;color:#FC3900'></i></center>
				  <hr>
				  <div class="row" style="height:auto;width:100%;border:0px solid black">
				  	<div class="col text-center"><h4 class="ml-3 mt-1"><b><%=link_to 'Pay Hostel Fee',new_student_hostelfee_path(current_user.id)%></b></h4>
				  	</div>
				  </div>
			</div>
		</div>
		<div class="col-sm-6 col-6 pl-5" style="border:0px solid black">
			  <div class="card mt-5 ml-5" style="border:2px solid orange;width:80%; float:left;border-radius:7%">
				  <center><i class='fas fa-question-circle mt-2' style='font-size:100px;color:#FC3900'></i></center>
				  <hr>
				  <div class="row" style="height:auto;width:100%;border:0px solid black">
				  	<div class="col text-center"><h4 class="ml-3 mt-1"><b><%=link_to 'Fee Receipt Status',student_hostelfee_path(current_user.id,1)%></b></h4>
				  	</div>
				  </div>
			</div>
	   </div>	
	</div>
</div>
</div>

app/views/hostelfee/new.html.erb
<%= render 'student/header' %>
<%= render 'student/menu' %>
<%if flash[:PaymentNotice]%>
                   <%=flash[:PaymentNotice]%>
                   <%end%>
<div style="height:auto;width:60%;margin-top:5%;margin-left:30%;border:2px solid orange;border-radius:5%" class="bg-light">
  
	   			<h2 class="pt-4 text-center"><b>Pay your hoatel fee</b></h2>
	   			<hr>
                   
                   <%= form_for @hostelfee,url:payment_index_path,method:'get' do |f| %>
                    <div class="row">
                        <div class="col-3 col-sm-3 "><h3 class="pl-4">Email:</h3></div>
                        <div class="col-5 col-sm-5 mb-5"><%=text_field_tag 'Email Id',current_user.email,class:'form-control',readonly:true%></div>
                        <div class="col-4 col-sm-4"></div>
                    </div>

                    <div class="row">
                        <div class="col-3 col-sm-3 "><h3 class="pl-4">Year:</h3></div>
                        <div class="col-5 col-sm-5 mb-5"><input type="text" class="form-control" readonly='true' value=<%=Date.today.year%>></div>
                        <div class="col-4 col-sm-4"></div>
                    </div>
                    <br><br>
                    <div class="row">
                        <div class="col-12 col-sm-12">
                        <center>
                        <%=f.submit 'Pay Now',class:'mb-3'%>
                        </center>
                        </div>
                    </div>
                   <% end %>
		   			
	   		</div>

app/views/hostelfee/show.html.erb
<%= render 'owner/header' %>
<%= render 'student/menu' %>
<div style="height:auto;width:60%;margin-top:5%;margin-left:30%;border:2px solid orange;border-radius:5%" class="bg-light">
	   			<h2 class="pt-4 text-center "><b>Fee Receipt Status</b></h2>
	   			<hr>
		   			<table class="table table-stripped table-hover table-bordered">
		   	<tr class="table-danger">		
		   	<td><b>No.</b></td>
			<td><b>Email</b></td>
			<td><b>Year</b></td>
			<td><b>Status</b></td>
			</tr>
			
			<%j=0%>
			 <%@hostelfee.each do |i|%>
			 <%j=j+1%>
			<tr>	
		   	<td><b><%=j%></b></td>
			<td><b><%=i.user.email%></b></td>	
			<td><b><%=i.year%></b></td>
			<td><b><%=i.status%></b></td>
			</tr>
			<%end%> 		   			
		   			</table>
	   		</div>
</div>