config/routes.rb
Rails.application.routes.draw do
  root to: 'hostel_operation#index'
  devise_for :users, controllers: {registrations: 'user/registrations' , sessions: 'user/sessions' }
  get 'owner/all_request'
  get 'owner/student_profile'
  get 'leave/show_owner'
  get 'room_management/get_all_room'
  resources :payment
  resources :hostel_operation
  post 'hostel_operation/check_auth'
  resources :room_management
  resources :owner
  resources :student do
    resources :leave
    resources :hostelfee
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/owner_controller.rb
class OwnerController < ApplicationController
    def index
         @owner=User.find_by(role:'owner')
         @total_rooms=Room.all.size
         @total_capacity=Room.sum('capacity');
         @total_vacancy=Room.sum('vacancy');
     end

    def new
        @user=User.new
    end

     def create    
         @user=User.new(get_paramas)
         @room=Room.find_by(room_no:@user.room_no)
         if @room==nil
             flash[:notice]='Room does not exist'
             redirect_to new_owner_path
         elsif @room.vacancy==0
             flash[:notice]='Not enough space in this room'
             redirect_to new_owner_path
         elsif @user.save(validate: false)
         	@room.vacancy=@room.vacancy-1
         	@room.save
             index
             render 'index'
         else
            flash[:notice]='Something went wrong'
             render 'new'
         end
     end
    
    def student_profile
        @user=User.find(params[:id])
    end
     def get_paramas
         params.require(:user).permit(:firstname,:lastname,:email,:phoneno,:username,:password,:role,:hostel_id,:room_no)
     end

    # def get_paramas
    #     params.require(:hosteler).permit(:firstname,:lastname,:email,:phoneno,:username,:password,:role,:hostel_id,:room_no)
    # end

    def all_request  
        @no_of_leave=Leave.where(status:'Pending').size
    end
end

app/helpers/owner_helper.rb
module OwnerHelper
end

app/views/owner/_header.html.erb
<nav class="navbar navbar-expand-sm text-white navbar-dark" style="border:2px solid black;background-color: #FF5C20;font-family: Montserrat, sans-serif;">  
    <img src="logo.png" alt="logo" style="width:7%;"> 
  	<h1 style="margin-left:20%"><b>Hostel Management System</b></h1>
</nav>

app/views/owner/_menu.html.erb
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<script src='https://kit.fontawesome.com/a076d05399.js' crossorigin='anonymous'></script>
<div>
	<table class="table table-hover table-striped" style="width:20%;background-color:#f4511e;float:left">
		<thead class="thead-dark">
			<tr>
				<th >Dashboard<i class="fa fa-dashboard  float-right" style="font-size:24px;color:white"></i>
				</th>
			</tr>
		</thead>
		<tbody>
			<tr>
				<td class="text-warning"><a href="#" class="link"><div style="height:100%;width:100%;"><i class='fas fa-home' style='font-size:35px;color:white;'></i><x class="ml-4" style="color:black"><b><%= link_to 'Home', owner_index_path,class:"link text-white" %></b></x></div></a>
				</td>
     		</tr>
      		<tr>
    			<th><a href="#" class="link text-white"><div style="height:100%;width:100%"><i class='fas fa-user-graduate' style='font-size:35px;color:white'></i><x class="ml-4" style="color:black"><b> View Student Info.</b></x></div></a>
    			</th>
    		</tr>
    		<tr>
  			    <th ><div style="height:100%;width:100%"><i class='fas fa-user-edit' style='font-size:40px;color:white'></i><x class="ml-4" style="color:black"><b><%= link_to 'Request', owner_all_request_path,class:"link text-white" %></b></x></div>
  			    </th>
  			</tr>
     		<tr>
    			<th><div style="height:100%;width:100%"><i class='fas fa-id-card' style='font-size:40px;color:white'></i><x class="ml-4" style="color:black"><%= link_to 'Generate Hostel Id', new_owner_path ,class:"link text-white"%></x></div>
					
				</th>
    		</tr>
    		<tr>
    			<th ><div style="height:100%;width:100%"><i class='fas fa-th-list' style='font-size:40px;color:white'></i> <x class="ml-4" style="color:black"><%= link_to 'Room Management', room_management_index_path ,class:"link text-white"%></x></div>
    			</th>
    		</tr>
     		<tr>
  			    <th><a href="#" class="link text-white"><div style="height:100%;width:100%"><i class='fa fa-bar-chart' style='font-size:40px;color:white'></i> <x class="ml-4" style="color:black"><b>Analysis</b></x></div></a>
  			    </th>
    		</tr>
    		<tr>
    			<th><a href="#" class="link text-white"><div style="height:100%;width:100%"><i class='fa fa-address-card-o' style='font-size:40px;color:white'></i><x class="ml-4" style="color:black"><b> Attendance</b></x></div></a>
    			</th>
    		</tr>
     		<tr>
    			<th><a href="#" class="link text-white "><div style="height:100%;width:100%"><i class='fa fa-exclamation-circle' style='font-size:40px;color:white'></i><x class="ml-4" style="color:black"><b> View Complains</b></x></div></a></th>
    		</tr>
    		<tr>
		     	<th ><a href="#" class="link text-white"><div style="height:100%;width:100%"><i class='fa fa-commenting' style='font-size:40px;color:white'></i><x class="ml-4" style="color:black"><b>Message for student</b></x></div></a></th>
		     </tr>
    		<tr>
    			<th ><div style="height:100%;width:100%"><i class='fa fa-sign-out' style='font-size:40px;color:white'></i> <x class="ml-4" style="color:black">
            <%= button_to 'Logout', destroy_user_session_path,class:"btn btn-danger",method:'delete',style:'margin-top:-10%;margin-left:35%'%>
            
    			</th>
   			 </tr>
		</tbody>
</table>
</div>

app/views/owner/_student.html.erb
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<script src='https://kit.fontawesome.com/a076d05399.js' crossorigin='anonymous'></script>
<div>
	<table class="table table-hover table-striped" style="width:20%;background-color:#f4511e;float:left">
		<thead class="thead-dark">
			<tr>
				<th >Dashboard<i class="fa fa-dashboard  float-right" style="font-size:24px;color:white"></i>
				</th>
			</tr>
		</thead>
		<tbody>
			<tr>
				<td class="text-warning"><a href="#" class="link"><div style="height:100%;width:100%;"><i class='fas fa-home' style='font-size:35px;color:white;'></i><x class="ml-4" style="color:black"><b><%= link_to 'Home', owner_index_path,class:"link text-white" %></b></x></div></a>
				</td>
     		</tr>
      		<tr>
    			<th><a href="#" class="link text-white"><div style="height:100%;width:100%"><i class='fas fa-user-graduate' style='font-size:35px;color:white'></i><x class="ml-4" style="color:black"><b> View Student Info.</b></x></div></a>
    			</th>
    		</tr>
    		<tr>
  			    <th ><div style="height:100%;width:100%"><i class='fas fa-user-edit' style='font-size:40px;color:white'></i><x class="ml-4" style="color:black"><b><%= link_to 'Request', owner_all_request_path,class:"link text-white" %></b></x></div>
  			    </th>
  			</tr>
     		<tr>
    			<th><div style="height:100%;width:100%"><i class='fas fa-id-card' style='font-size:40px;color:white'></i><x class="ml-4" style="color:black"><%= link_to 'Generate Hostel Id', new_owner_path ,class:"link text-white"%></x></div>
					
				</th>
    		</tr>
    		<tr>
    			<th ><div style="height:100%;width:100%"><i class='fas fa-th-list' style='font-size:40px;color:white'></i> <x class="ml-4" style="color:black"><%= link_to 'Room Management', room_management_index_path ,class:"link text-white"%></x></div>
    			</th>
    		</tr>
     		<tr>
  			    <th><a href="#" class="link text-white"><div style="height:100%;width:100%"><i class='fa fa-bar-chart' style='font-size:40px;color:white'></i> <x class="ml-4" style="color:black"><b>Analysis</b></x></div></a>
  			    </th>
    		</tr>
    		<tr>
    			<th><a href="#" class="link text-white"><div style="height:100%;width:100%"><i class='fa fa-address-card-o' style='font-size:40px;color:white'></i><x class="ml-4" style="color:black"><b> Attendance</b></x></div></a>
    			</th>
    		</tr>
     		<tr>
    			<th><a href="#" class="link text-white "><div style="height:100%;width:100%"><i class='fa fa-exclamation-circle' style='font-size:40px;color:white'></i><x class="ml-4" style="color:black"><b> View Complains</b></x></div></a></th>
    		</tr>
    		<tr>
		     	<th ><a href="#" class="link text-white"><div style="height:100%;width:100%"><i class='fa fa-commenting' style='font-size:40px;color:white'></i><x class="ml-4" style="color:black"><b>Message for student</b></x></div></a></th>
		     </tr>
    		<tr>
    			<th ><div style="height:100%;width:100%"><i class='fa fa-sign-out' style='font-size:40px;color:white'></i> <x class="ml-4" style="color:black">
            <%= button_to 'Logout_devise', destroy_hosteler_session_path,class:"link text-white",method:'delete'%>
            <%= link_to 'Logout', hostel_operation_index_path ,class:"link text-white"%>
    			</th>
   			 </tr>
		</tbody>
</table>
</div>

app/views/owner/all_request.html.erb
<%= render 'header' %>
<%= render 'menu' %>
<div class="container">
	<div class="row mt-5">
		<div class="col-lg-6 col-md-6 col-12" style="border:0px solid black">
			 <a href="#"><div class="card mt-5 ml-5" style="border:2px solid orange;width:80%; float:left;border-radius:7%">
				  <center><i class='fas fa-exclamation-triangle mt-2' style='font-size:100px;color:#FC3900'></i></center>
				  <hr>
				  <div class="row" style="height:auto;width:100%;border:0px solid black">
				  	<div class="col col-7"><h4 class="ml-3 mt-1"><b>Fee Request</b></h4>
				  	</div>
				  	<div class="col col-2"><div style="height:90%;width:1%;border:2px solid black"></div>
				  	</div>
				  	<div class="col col-3"><h4 class=" mt-1"><b>0</b></h4>
				  	</div>
				  </div>
			</div></a>
			<a href="#"><div class="card mt-5 ml-5" style="border:2px solid orange;width:80%; float:left;border-radius:7%">
					<center><i class='fas fa-bed mt-2' style='font-size:100px;color:#FC3900'></i></center>
				  <hr>
				  <div class="row" style="height:auto;width:100%;border:0px solid black">
				  	<div class="col col-7"><h4 class="ml-3 mt-1"><b>Guest's Stay</b></h4>
				  	</div>
				  	<div class="col col-2"><div style="height:90%;width:1%;border:2px solid black"></div>
				  	</div>
				  	<div class="col col-3"><h4 class=" mt-1"><b>0</b></h4>
				  	</div>
				  </div>				 
			</div></a>
		</div>
		<div class="col-lg-6 col-md-6 col-12" style="border:0px solid black">
			 <div class="card mt-5 ml-5" style="border:2px solid orange;width:80%; float:left;border-radius:7%">
				  <center><i class='fa fa-building mt-2' style='font-size:100px;color:#FC3900'></i></center>
				  <hr>
				  <div class="row" style="height:auto;width:100%;border:0px solid black">
				  	<div class="col col-7"><h4 class="ml-3 mt-1"><b><%=link_to 'Leave Request',leave_show_owner_path%></b></h4>
				  	</div>
				  	<div class="col col-2"><div style="height:90%;width:1%;border:2px solid black"></div>
				  	</div>
				  	<div class="col col-3"><h4 class=" mt-1"><b><%=@no_of_leave%></b></h4>
				  	</div>
				  </div>
			</div>
			<a href="#"><div class="card mt-5 ml-5" style="border:2px solid orange;width:80%; float:left;border-radius:7%">
				  <center><i class='fas fa-concierge-bell mt-2' style='font-size:100px;color:#FC3900'></i></center>
				  <hr>
				  <div class="row" style="height:auto;width:100%;border:0px solid black">
				  	<div class="col col-7"><h4 class="ml-3 mt-1"><b>Food Coupon</b></h4>
				  	</div>
				  	<div class="col col-2"><div style="height:90%;width:1%;border:2px solid black"></div>
				  	</div>
				  	<div class="col col-3"><h4 class=" mt-1"><b>0</b></h4>
				  	</div>
				  </div>
			</div></a>
		</div>
	</div>
</div>
</div>

app/views/owner/index.html.erb
<%= render 'header' %>
<%= render 'menu' %>

<div style="height:auto;width:70%;margin-top:2%;margin-left:25%;border:2px solid orange;border-radius:5%" class="bg-light">   			
		   			
		   				<div class="row pl-5">
						    <div class="col">
						    	
					<center><h3 class="pt-4 text-center"><b> Hello <%=@owner.firstname%> Welcome to Owner Portal </b></h3>
	   			<hr><br></center>
						
						
					<center><h5><b>General Information</b></h5></center><br>
					<b>Mobile Number:    <%=@owner.phoneno%></b><br>

						<b> Email Id:      <%=@owner.email%></b><br>
						
						<b>hosteladdress:     <%=@owner.address%></b>


						    </div>
						  </div><br>
						  
						  
						  <div class="row pl-5">
							   <div class="col">
							    	<center> <h5><b>Hostel Information:</b></h5></center>
							    </div>
						  </div><br>
							  
						  <div class="row pl-5">
							   <div class="col">
							    	<h5><b>About no of room:</b></h5>
							    </div>
						  </div>
						  
						  <div class="row pl-5">
							    <div class="col">
							    	<b>Total no of room = <%=@total_rooms%></b>
							    </div>
							    <div class="col">
							    	<b>No of student's room = <%=@total_rooms%></b>
							    </div>
							    <div class="col">
							    	<b>No of guest's rooms = 0</b>
							    </div>
						  </div><br>
						  
						  <div class="row pl-5">
							   <div class="col">
							    	<h5><b>About capacity of hostel:</b></h5>
							    </div>
						  </div>
						  
						  <div class="row pl-5">
							    <div class="col">
							    	<b>Capacity for students = <%=@total_capacity%></b>
							    </div>
							    <div class="col">
							    	<b>No of students in hostel  = <%=@total_capacity-@total_vacancy%></b>
							    </div>
							    <div class="col">
							    	<b>Vacancy in hostel = <%=@total_vacancy%></b>
							    </div>
						  </div><br>
						   
					
	   		</div>

app/views/owner/new.html.erb
<%= render 'header' %>
<%= render 'menu' %>
<%if flash[:notice]%>
<%=flash[:notice]%>	
<%end%>
<div style="height:auto;width:50%;margin-top:5%;margin-left:35%;border:2px solid orange;border-radius:5%" class="bg-light">
	   			<h2 class="pt-4 text-center"><b>Generate Hostel-Id</b></h2>
	   			<hr>
		   			<%=form_for @user,url:owner_index_path,method:'post' do |f|%>
						  <div class="row pl-5">
						    <div class="col">
						      <label class="pt-2"><b>Email</b></label>
                              <%=f.text_field :email,class:'form-control w-50'%>
								<span style='color:red'><%=@user.errors[:username].to_sentence%></span>
						    </div>
						  </div>
						  <div class="row pl-5">
						    <div class="col">
						      <label class="pt-2"><b>Room No</b></label>
                              <%=f.text_field :room_no,class:'form-control w-50'%>
							  <span style='color:red'><%=@user.errors[:room_no].to_sentence%></span>
						    </div>
						  </div>
						  <div class="row pl-5">
						    <div class="col">
						      <label class="pt-2"><b>Password</b></label>
                              <%=f.text_field :password,class:'form-control w-50'%>
							  <span style='color:red'><%=@user.errors[:password].to_sentence%></span>
						    </div>
						  </div>
						  <div class="row pl-5 pb-5">
						    <div class="col">
                            <%=f.submit 'Generate Id'%>
						    </div>
						  </div>  
					<%end%>
	   		</div>

app/views/owner/student_profile.html.erb
<%= render 'header' %>
<%= render 'menu' %>
<div id="profile" style="height:auto;width:60%;margin-top:5%;margin-left:30%;border:2px solid orange;border-radius:5%" class="bg-light">
		 <center><div class="mt-3">
		<%if current_user.ProfilePic.attached?%>
		 	<image src=<%=url_for(@user.ProfilePic)%> height="350px" width="30%">
		 <%end%>
		 	</div></center>
	  <center><table class="information_table" style="margin-right:15%">
	   <center> <tr>
	   <th><p>Name:</p></th><td></td> 
	   <td><p><%=@user.firstname%> <%=@user.lastname%> </p></td>
	   </tr>
	  
	   <tr>
	   <th><p>Email:</p></th><td></td>
	   <td><p><%=@user.email%></p></td>
	   </tr>
	   
	   <tr>
	   <th><p>Mobile No:</p></th><td></td>
	   <td><p><%=@user.phoneno%></p></td>
	   </tr>
		
	   
		<br>			
	   </table></center><br><br>
	   <div class="mb-5 ml-5">
 <h4><b>History Of Student</b></h4><br>
	<a href="ownerfeestatus.html?hostelid=${hostelid}">Fee Requests Details</a><br>
	<a href="ownergueststaystatus.html?hostelid=${hostelid}">Guests Night Stay Requests Details</a><br>
	<a href="ownerleaveapplicationstatus.html?hostelid=${hostelid}">Leave Requests Details</a><br>
	<a href="ownerfoodstatus.html?hostelid=${hostelid}">Food Coupon Requests Details</a><br><br>
	</div>	
</div>